# Generated by Django 4.1.3 on 2022-11-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_changepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addtocart',
            name='total',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
