# Generated by Django 4.1.3 on 2022-11-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subbanners',
            old_name='sub_banner1',
            new_name='subbanner1',
        ),
        migrations.RenameField(
            model_name='subbanners',
            old_name='sub_banner2',
            new_name='subbanner2',
        ),
    ]
