# Generated by Django 4.1.3 on 2022-11-15 05:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_headerflash_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_image1',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/'),
        ),
    ]
