# Generated by Django 4.1.3 on 2022-11-22 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.coupon'),
        ),
    ]
