# Generated by Django 4.1.3 on 2022-11-15 05:19

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_product_sub_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_image2',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_image3',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='products/'),
        ),
    ]
