# Generated by Django 4.1.3 on 2022-12-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_cashondeliveyorders_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashondeliveyorders',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
