# Generated by Django 4.1.3 on 2022-12-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ordertracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='Delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='DeliveredDateAndime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='Shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='ShippedTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='orderPlaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='orderPlacedtime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='preparingToShip',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ordertracking',
            name='preparingToShiptime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
