# Generated by Django 4.1.3 on 2022-12-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_cashondeliveyorders_order_date_order_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='added_date',
        ),
        migrations.AlterField(
            model_name='cashondeliveyorders',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
