# Generated by Django 4.1.3 on 2022-12-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_ordertracking_delivered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='ShippedTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
