# Generated by Django 4.1.3 on 2022-12-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_ordertracking_shippedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertracking',
            name='orderPlacedtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordertracking',
            name='preparingToShiptime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
