# Generated by Django 4.1.3 on 2022-12-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_ordertracking_orderplacedtime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertracking',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.order'),
        ),
    ]
