# Generated by Django 4.1.3 on 2022-12-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_ordertracking_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertracking',
            old_name='DeliveredDateAndime',
            new_name='DeliveredDateAndTime',
        ),
    ]
