from django.urls import path,include
from . import views

app_name = "user"
urlpatterns = [
    path("test", views.test, name="test"),
    path("about-us.html", views.about_us, name="about_us"),
    path("blog-detail.html", views.blog_detail, name="blog_detail"),
    path("blog-grid.html", views.blog_grid, name="blog_grid"),
    path("blog-list.html", views.blog_list, name="blog_list"),
    path("cart.html", views.cart, name="cart"),
    path("checkout.html", views.checkout, name="checkout"),
    path("coming-soon.html", views.coming_soon, name="coming_soon"),
    path("compare.html", views.compare, name="compare"),
    path("contact-us.html", views.contact_us, name="contact_us"),
    path("faq.html", views.faq, name="faq"),
    path("forgot.html", views.forgot, name="forgot"),
    path("index-2.html", views.index_2, name="index_2"),
    path("index-3.html", views.index_3, name="index_3"),
    path("index-4.html", views.index_4, name="index_4"),
    path("index-5.html", views.index_5, name="index_5"),
    path("index-6.html", views.index_6, name="index_6"),
    path("index-7.html", views.index_7, name="index_7"),
    path("index-8.html", views.index_8, name="index_8"),
    path("index-9.html", views.index_9, name="index_9"),
    path("", views.index, name="index"),
    path("login.html", views.login, name="login"),
    path("order-success.html", views.order_success, name="order_success"),
    path("order-tracking.html", views.order_tracking, name="order_tracking"),
    path("otp.html", views.otp, name="otp"),
    path("product-4-image.html", views.product_4_image, name="product_4_image"),
    path("product-bottom-thumbnail.html", views.product_bottom_thumbnail, name="product_bottom_thumbnail"),
    path("product-bundle.html", views.product_bundle, name="product_bundle"),
    path("product-left-thumbnail.html", views.product_left_thumbnail, name="product_left_thumbnail"),
    path("product-right-thumbnail.html", views.product_right_thumbnail, name="product_right_thumbnail"),
    path("product-slider.html", views.product_slider, name="product_slider"),
    path("product-sticky.html", views.product_sticky, name="product_sticky"),
    path("search.html", views.search, name="search"),
    path("seller-become.html", views.seller_become, name="seller_become"),
    path("seller-dashboard.html", views.seller_dashboard, name="seller_dashboard"),
    path("seller-detail-2.html", views.seller_detail_2, name="seller_detail_2"),
    path("seller-detail.html", views.seller_detail, name="seller_detail"),
    path("seller-grid-2.html", views.seller_grid_2, name="seller_grid_2"),
    path("seller-grid.html", views.seller_grid, name="seller_grid"),
    path("shop-banner.html", views.shop_banner, name="shop_banner"),
    path("shop-category-slider.html", views.shop_category_slider, name="shop_category_slider"),
    path("shop-category.html", views.shop_category, name="shop_category"),
    path("shop-left-sidebar.html", views.shop_left_sidebar, name="shop_left_sidebar"),
    path("shop-list.html", views.shop_list, name="shop_list"),
    path("shop-right-sidebar.html", views.shop_right_sidebar, name="shop_right_sidebar"),
    path("shop-top-filter.html", views.shop_top_filter, name="shop_top_filter"),
    path("sign-up.html", views.sign_up, name="sign_up"),
    path("user-dashboard.html", views.user_dashboard, name="user_dashboard"),
    path("wishlist.html", views.wishlist, name="wishlist"),
    path("404.html", views.error_404, name="error_404"),
    
]
